name: chatgpt-desktop
base: core20
version: '1.0.0'
summary: Unofficial ChatGPT Desktop Client
description: |
  A simple and efficient desktop client for chatgpt, using Electron to provide a seamless experience.

grade: stable
confinement: strict

apps:
  chatgpt-desktop:
    command: chatgpt-desktop-client
    extensions: [gnome-3-38]
    plugs:
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl

parts:
  chatgpt-desktop:
    plugin: dump
    source: .
    stage-packages:
      - libnss3
      - libxss1
      - libgtk-3-0
    after:
      - desktop-gtk3
